---
# Import the asset

- name: Import json asset - {{ item.name }}
  awx.awx.import:
    assets: "{{ lookup('file', '{{ item.path }}') | from_json() }}"
    controller_host: "{{ controller_host }}"
    controller_username: "{{ controller_username }}"
    controller_password: "{{ controller_password }}"
    validate_certs: false
  register: result
  when: backup_type == "json"

- name: Import json asset - {{ item.name }} from {{ item.path }}
  awx.awx.import:
    assets: "{{ lookup('file', '{{ item.path }}') | from_yaml() }}"
    controller_host: "{{ controller_host }}"
    controller_username: "{{ controller_username }}"
    controller_password: "{{ controller_password }}"
    validate_certs: false
  register: result
  when: backup_type == "yml"

  
# - debug:
#     var: result
  